version: "3"
services:
  node:
    container_name: "qnx"
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm start"